export const MUSIC_LIST_REQUEST = 'MUSIC_LIST_REQUEST'
export const MUSIC_LIST_SUCCESS = 'MUSIC_LIST_SUCCESS'
export const MUSIC_LIST_FAIL = 'MUSIC_LIST_FAIL'

export const MUSIC_DETAILS_REQUEST = 'MUSIC_DETAILS_REQUEST'
export const MUSIC_DETAILS_SUCCESS = 'MUSIC_DETAILS_SUCCESS'
export const MUSIC_DETAILS_FAIL = 'MUSIC_DETAILS_FAIL'

export const MUSIC_DELETE_REQUEST = 'MUSIC_DELETE_REQUEST'
export const MUSIC_DELETE_SUCCESS = 'MUSIC_DELETE_SUCCESS'
export const MUSIC_DELETE_FAIL = 'MUSIC_DELETE_FAIL'

export const MUSIC_CREATE_REQUEST = 'MUSIC_CREATE_REQUEST'
export const MUSIC_CREATE_SUCCESS = 'MUSIC_CREATE_SUCCESS'
export const MUSIC_CREATE_FAIL = 'MUSIC_CREATE_FAIL'
export const MUSIC_CREATE_RESET = 'MUSIC_CREATE_RESET'

export const MUSIC_UPDATE_REQUEST = 'MUSIC_UPDATE_REQUEST'
export const MUSIC_UPDATE_SUCCESS = 'MUSIC_UPDATE_SUCCESS'
export const MUSIC_UPDATE_FAIL = 'MUSIC_UPDATE_FAIL'
export const MUSIC_UPDATE_RESET = 'MUSIC_UPDATE_RESET'

export const MUSIC_CREATE_VOTE_REQUEST = 'MUSIC_CREATE_VOTE_REQUEST'
export const MUSIC_CREATE_VOTE_SUCCESS = 'MUSIC_CREATE_VOTE_SUCCESS'
export const MUSIC_CREATE_VOTE_FAIL = 'MUSIC_CREATE_VOTE_FAIL'
export const MUSIC_CREATE_VOTE_RESET = 'MUSIC_CREATE_VOTE_RESET'

export const MUSIC_TOP_REQUEST = 'MUSIC_TOP_REQUEST'
export const MUSIC_TOP_SUCCESS = 'MUSIC_TOP_SUCCESS'
export const MUSIC_TOP_FAIL = 'MUSIC_TOP_FAIL'


export const MUSIC_SEARCH_REQUEST = 'MUSIC_SEARCH_REQUEST'
export const MUSIC_SEARCH_SUCCESS = 'MUSIC_SEARCH_SUCCESS'
export const MUSIC_SEARCH_FAIL = 'MUSIC_SEARCH_FAIL'
export const MUSIC_SEARCH_RESET = 'MUSIC_SEARCH_RESET'